######

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: "data/tumor_vs_ec/age_vs_young.tsv" #### Sample sheet
gene_name_type: ENSEMBL # ENSEMBL or HGNC Or ENTREZ_ID
organism: "Mus musculus" # Name of Organsim sequenced (Supported: Mus Musculus, Homo sapiens)
SEQ_TYPE: "paired"

### Data Dirs ###
dirs:
  BASE_DATA_DIR: "/omics/odcf/project/OE0228/VascularAgeing/sequencing/rna_sequencing/view-by-pid"
  BASE_ANALYSIS_DIR: "/omics/odcf/analysis/OE0228_projects/VascularAging/rna_sequencing/tec_age_vs_young/"

## Configuration
pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition
    - age
    - cell_type

diffexp:
  gsea_use_stat: True
  pval_threshold: 0.05
  LFC_threshold: 0.5
  shrink_lfc:
    True
    # contrasts for the deseq2 results method
  contrasts:
    condition: # Here column in sample sheet
      aged_tumor_vs_young_tumor: # comparison
        - aged_tumor
        - young_tumor
      aged_ec_vs_young_ec:
        - aged_ec
        - young_ec
      aged_tumor_vs_aged_ec:
        - aged_tumor
        - aged_ec
      young_tumor_vs_young_ec:
        - young_tumor
        - young_ec
    cell_type:
      tumor_vs_endo:
        - tumor
        - endo_cell
    age:
      aged_vs_young:
        - aged
        - young
  model: "~condition"
  custom_model:
    cell_type: "~cell_type + age"
    age: "~cell_type + age"
  filter_samples:
    condition: True
    cell_type: False
    age: False

gsea:
  Hallmark_gsea:
    category: H
    subcategory: NULL
    use_gsea: True
    database: MSigDB
    id_class: ENSEMBL
  Hallmark_fisher:
    category: H
    subcategory: NULL
    use_gsea: False
    database: MSigDB
    id_class: ENSEMBL
  MsigDB_C2:
    category: C2
    subcategory: NULL
    use_gsea: True
    database: MSigDB
    id_class: ENSEMBL
  MsigDB_C5:
    category: C5
    subcategory: NULL
    use_gsea: True
    database: MSigDB
    id_class: ENSEMBL
  MsigDB_C8:
    category: C8
    subcategory: NULL
    use_gsea: True
    database: MSigDB
    id_class: ENSEMBL
  MsigDB_C3:
    category: C3
    subcategory: NULL
    use_gsea: True
    database: MSigDB
    id_class: ENSEMBL
  Reactome_GSEA:
    category: NULL
    subcategory: NULL
    use_gsea: True
    database: Reactome
    id_class: ENTREZID
  EC_senesence:
    category: NULL
    subcategory: NULL
    use_gsea: True
    database: custom_senescence
    id_class: ENSEMBL
  MitoCarta:
    category: NULL
    subcategory: NULL
    use_gsea: True
    database: MitoCarta
    id_class: ENSEMBL
## Color control
group_colors:
  condition:
    aged_tumor: "#01A2A2"
    young_tumor: "#A2A201"
    aged_ec: "#A00101"
    young_ec: "grey"
  cell_type:
    tumor: "red"
    endo_cell: "blue"
  age:
    young: "yellow"
    aged: "black"

# Workflow control and management
run_mitch: False
run_carnival:
  vanilla: False
  inverse: False
  sample: False
  joint_rep: False

cplex_solver: "/home/heyer/software/external/CPLEX_Studio201/cplex/bin/x86-64_linux/cplex"

DKFZ: True
units: "data/tumor_vs_ec/units_a_v_y.tsv"

ref:
  # the STAR indexjjj
  index: "/omics/odcf/reference_data/legacy/ngs_share/assemblies/mm10/indexes/STAR/STAR_2.5.2b_GRCm38mm10_gencodevM12_PhiX_100bp"
  # gtf file with transcripts
  annotation: "/omics/odcf/reference_data/legacy/ngs_share/assemblies/mm10/databases/gencode/gencodeM12/gencode.vM12.annotation.GRCm38mm10_Phix.gtf"
  ## kallisto
  #
glmmseq:
